### ISSUE TITLE
guess the word minigame for `beg` command

### ISSUE THREAD

**Issue by schlopp** [schlopp/ppbot-v2#25]
There should be a 5% chance that when a user runs `{prefix}beg`, they're given a sentence with one word removed. The user then has to type that word in chat. The sentences used for this command should be quotes from memes, movies, etc, like the minigame for `pp hunt` in the old pp bot. The dialogue leading up to this minigame should change based on the location. There should also be a special reward given to users who complete the minigame.

Example:
user: {prefix}beg
pp bot: *Select a location prompt*
user: *Selects "Under A Bridge"*
pp bot: While you're begging bypassers to give you inches, you notice a homeless guy high on meth. He's trying to tell you something, but you can't make out what he's saying. Guess what the missing word is!
homeless guy: "Whoever threw that paper, your mom's a `___`"
user: hoe
pp bot: *gives special reward and continues with the beg command*

**Comment by schlopp** [comment]
Example:
```toml
[[locations]]
    level = 0
    id = "BRIDGE"
    emoji = "😔"
    name = "Under a Bridge"
    description = "Lmao broke boy go beg with the other homeless"

    [locations.quotes]
        fail = [
            "Damn bro I live under a bridge and you're asking ME for inches??",
            "What did you think was gonna happen when you asked some homeless dude for inches",
            "Sorry I spent all my inches on meth",
        ]

        [locations.quotes.minigames]

            [locations.quotes.minigames.fillintheblank]
                context = "While you're begging bypassers to give you inches, you notice a homeless guy high on meth. He's trying to tell you something, but you can't make out what he's saying."
                success = "Man I'm high as fuck, I think I'ma pass out. You can keep my stuff, {0}, incase I die"
                fail = "The meth addicted looks cries and runs away. You have no idea what just happened."
```
